apiVersion: apps/v1
kind: Deployment
metadata:
  name: jamongx-user-service
  labels:
     app: user-service

spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: jamongx/twitter-clone-user-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1