---
- hosts: kubernetes
#  become: true
  user: root

  tasks:
  - name: deploy user-service on kubernetes
    command: kubectl apply -f user-service-deployment.yml

  - name: create service for user-service
    command: kubectl apply -f user-service-service.yml

  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.apps/jamongx-user-service